'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WebApplication1.CustomControls

    Partial Public Class CustomAppointmentForm

        '''<summary>
        '''ASPxLabelSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxLabelSubject As Global.DevExpress.Web.ASPxLabel

        '''<summary>
        '''ASPxTextBoxSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxTextBoxSubject As Global.DevExpress.Web.ASPxTextBox

        '''<summary>
        '''ASPxLabelStart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxLabelStart As Global.DevExpress.Web.ASPxLabel

        '''<summary>
        '''ASPxDateEditStart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxDateEditStart As Global.DevExpress.Web.ASPxDateEdit

        '''<summary>
        '''ASPxLabelEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxLabelEnd As Global.DevExpress.Web.ASPxLabel

        '''<summary>
        '''ASPxDateEditEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxDateEditEnd As Global.DevExpress.Web.ASPxDateEdit

        '''<summary>
        '''ASPxMemoDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxMemoDescription As Global.DevExpress.Web.ASPxMemo

        '''<summary>
        '''lblResource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResource As Global.DevExpress.Web.ASPxLabel

        '''<summary>
        '''ddResource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddResource As Global.DevExpress.Web.ASPxDropDownEdit

        '''<summary>
        '''edtResource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents edtResource As Global.DevExpress.Web.ASPxComboBox

        '''<summary>
        '''chkReminder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkReminder As Global.DevExpress.Web.ASPxCheckBox

        '''<summary>
        '''lblReminder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReminder As Global.DevExpress.Web.ASPxLabel

        '''<summary>
        '''cbReminder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbReminder As Global.DevExpress.Web.ASPxComboBox

        '''<summary>
        '''ASPxLabelCompany control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxLabelCompany As Global.DevExpress.Web.ASPxLabel

        '''<summary>
        '''ASPxComboBoxCompany control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxComboBoxCompany As Global.DevExpress.Web.ASPxComboBox

        '''<summary>
        '''ASPxLabelContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxLabelContact As Global.DevExpress.Web.ASPxLabel

        '''<summary>
        '''ASPxComboBoxContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxComboBoxContact As Global.DevExpress.Web.ASPxComboBox

        '''<summary>
        '''AppointmentRecurrenceForm1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AppointmentRecurrenceForm1 As Global.DevExpress.Web.ASPxScheduler.Controls.AppointmentRecurrenceForm

        '''<summary>
        '''ASPxButtonOk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxButtonOk As Global.DevExpress.Web.ASPxButton

        '''<summary>
        '''ASPxButtonCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxButtonCancel As Global.DevExpress.Web.ASPxButton

        '''<summary>
        '''ASPxButtonDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxButtonDelete As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
